---
- name: user
  hosts: demo
  tasks:
    - name: Preconfig block
      block:
        - name: Create_user
          vars:
            user: firedemon
          user:
            name: "{{ user }}"
            state: present
          register: error
        - name: Install curl
          apt:
            name: curl
            update-cache: yes
          register: error
      become: true
      rescue:
        - name: Some error output
          debug:
            var: error
      always:
        - name: Reboot
          debug:
            msg: "Reboot!!!"