---
- name: user
  hosts: demo
  tasks:
    - name: Create_user
      vars:
        user: firedemon
      user:
        name: "{{ user }}"
        state: present
      become: true
      register: out
    - debug:
        var: out

# ansible-playbook -i demo-server user.yml -K