---
- name: user
  hosts: demo
  tasks:
    - name: Create_user
      user:
        name: "{{ user }}"
        state: present
      become: true


# вместо  ansible-playbook -i hosts.ini user.yml -K используем  ansible-playbook -i demo-server user.yml -K 
# группа серверов, група переменных, и сам файл