---
- name: user
  hosts: demo
  # any_error_fatal: true / false
  tasks:
    - name: Preconfig block
      block:
        - name: Create_user
          vars:
            user: firedemon
          user:
            name: "{{ user }}"
            state: present
          register: error
        # ignore_errors: yes пропускает ошибки в таске/блоке и не уходим в rescue
        - name: Install curl
          apt:
            name: curl
            update-cache: yes
          register: error
      become: true
      when: ansible_facts['distribution']=='Ubuntu'
      rescue:
        - name: Some error output
          debug:
            var: error
      always:
        - name: Reboot
          debug:
            msg: "Reboot!!!"